package zed.rainxch.apps.presentation.mappers

import zed.rainxch.apps.presentation.model.InstalledAppUi
import zed.rainxch.core.domain.model.InstalledApp

fun InstalledApp.toUi(): InstalledAppUi =
    InstalledAppUi(
        repoId = repoId,
        repoName = repoName,
        repoOwner = repoOwner,
        repoOwnerAvatarUrl = repoOwnerAvatarUrl,
        repoDescription = repoDescription,
        primaryLanguage = primaryLanguage,
        repoUrl = repoUrl,
        installedVersion = installedVersion,
        installedAssetName = installedAssetName,
        installedAssetUrl = installedAssetUrl,
        latestVersion = latestVersion,
        latestAssetName = latestAssetName,
        latestAssetUrl = latestAssetUrl,
        latestAssetSize = latestAssetSize,
        installSource = installSource,
        installedAt = installedAt,
        lastCheckedAt = lastCheckedAt,
        lastUpdatedAt = lastUpdatedAt,
        isUpdateAvailable = isUpdateAvailable,
        updateCheckEnabled = updateCheckEnabled,
        releaseNotes = releaseNotes,
        systemArchitecture = systemArchitecture,
        fileExtension = fileExtension,
        isPendingInstall = isPendingInstall,
        installedVersionName = installedVersionName,
        installedVersionCode = installedVersionCode,
        latestVersionName = latestVersionName,
        latestVersionCode = latestVersionCode,
        packageName = packageName,
        appName = appName,
        signingFingerprint = signingFingerprint,
    )

fun InstalledAppUi.toDomain(): InstalledApp =
    InstalledApp(
        repoId = repoId,
        repoName = repoName,
        repoOwner = repoOwner,
        repoOwnerAvatarUrl = repoOwnerAvatarUrl,
        repoDescription = repoDescription,
        primaryLanguage = primaryLanguage,
        repoUrl = repoUrl,
        installedVersion = installedVersion,
        installedAssetName = installedAssetName,
        installedAssetUrl = installedAssetUrl,
        latestVersion = latestVersion,
        latestAssetName = latestAssetName,
        latestAssetUrl = latestAssetUrl,
        latestAssetSize = latestAssetSize,
        installSource = installSource,
        installedAt = installedAt,
        lastCheckedAt = lastCheckedAt,
        lastUpdatedAt = lastUpdatedAt,
        isUpdateAvailable = isUpdateAvailable,
        updateCheckEnabled = updateCheckEnabled,
        releaseNotes = releaseNotes,
        systemArchitecture = systemArchitecture,
        fileExtension = fileExtension,
        isPendingInstall = isPendingInstall,
        installedVersionName = installedVersionName,
        installedVersionCode = installedVersionCode,
        latestVersionName = latestVersionName,
        latestVersionCode = latestVersionCode,
        packageName = packageName,
        appName = appName,
        signingFingerprint = signingFingerprint,
    )
